import { Metadata } from 'next';
import './global.css';
export const metadata: Metadata = {
  title: { template: '%s | Page', default: 'Home' },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
